sudo: false
language: python
python:
  - '3.5'
install:
  - pip install -r requirements.txt
  - npm install
script:
  - gulp scss
  - py.test --flake8 --cov=app
addons:
  apt:
    packages:
      - nodejs
