apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dasher-deployment

spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dasher
    spec:
      containers:
        - name: uwsgi
          imagePullPolicy: "Always"
          image: "lsstsqre/ltd-dasher:v0.1.1"
          ports:
            - containerPort: 3031
              name: dasher
          readinessProbe:
            httpGet:
              path: /healthz
              port: dasher
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: LTD_DASHER_PROFILE
              value: production
            - name: LTD_DASHER_AWS_ID
              valueFrom:
                secretKeyRef:
                  name: dasher-secrets
                  key: aws-id
            - name: LTD_DASHER_AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: dasher-secrets
                  key: aws-secret
            - name: LTD_DASHER_FASTLY_ID
              valueFrom:
                secretKeyRef:
                  name: dasher-secrets
                  key: fastly-id
            - name: LTD_DASHER_FASTLY_KEY
              valueFrom:
                secretKeyRef:
                  name: dasher-secrets
                  key: fastly-key

