name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: py.test --flake8 --cov=app

  build:
    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - uses: actions/checkout@v2

      - name: Define the Docker tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF} | sed -E 's,refs/(heads|tags)/,,' | sed -E 's,/,-,g')

      - name: Print the tag
        id: print
        run: echo ${{steps.vars.outputs.tag}}

      - name: Log into Docker Hub
        if: ${{ github.event_name == 'push' }}
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      - name: Install npm packages
        run: npm install .

      - name: Create assets
        run: gulp assets --env=deploy

      - name: Build the runtime Docker image
        run: |
          docker build --tag lsstsqre/ltd-dasher:${{steps.vars.outputs.tag}} .

      - name: Push Docker images
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push lsstsqre/ltd-dasher:${{steps.vars.outputs.tag}}
